project 'Marklight Sample'
use_frameworks!

abstract_target 'Marklight' do
  pod 'Marklight', :path => '..'
  
  target 'Marklight Sample' do
    platform :ios, '8.0'
  end
  
  target 'Marklight Sample macOS' do
    platform :osx, '10.11'
  end
end
